<font color='green'>

# Array Olusturma

### numpy array'i numpy kütüphanesi içerisinde yer alan tıpkı listeler gibi sözlükler gibi bir veri tipidir. 

### iki yolu vardır. Birincisi bir liste üzerinden array oluşturma yöntemidir:

In [6]:
import numpy as np

In [ ]:
"""" Öncelikle numpy kütüphanemizi import ediyoruz ve 'np' kısaltmasıyla 
kullanacağımızı python'a bildiriyoruz. """"

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

### İkincisi ise sıfırdan array oluşturma yöntemidir. Elimizde incelemek üzere bir verimiz olduğu zaman ihtiyacı en çok çözen yöntemdir Birkaç yöntemi birlikte inceleyelim.

* 0'lardan oluşan int tipinde 10 elemanlı tek boyutlu bir array oluşturalım:

In [9]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

* 3'e 5 ve 1'lerden oluşan bir matris yapısı tanımlayalım. '3'e 5' lafından da anlaşılacağı üzre iki boyutlu bir array oluşturacağız:

In [13]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

* İstediğimiz herhangi bir rakamda 3'e 5'lik bir matris olusturalım. Ben sadece 5'lerden oluşan bir matris yapmak istiyorum :

In [14]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

* 0'dan 30'e kadar 3'er 3'er artacak şekilde doğrusal bir dizi oluşturalım: