<font color='green'>

# Array Olusturma

### numpy array'i numpy kütüphanesi içerisinde yer alan tıpkı listeler gibi sözlükler gibi bir veri tipidir. 

### iki yolu vardır. Birincisi bir liste üzerinden array oluşturma yöntemidir:

In [6]:
import numpy as np

In [ ]:
""" Öncelikle numpy kütüphanemizi import ediyoruz ve 'np' kısaltmasıyla 
kullanacağımızı python'a bildiriyoruz."""

Eğer numpy kütüphanemiz python'da yüklü değil ise **'pip install numpy'** yazarak kütüphanemizi indirebiliriz.

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

### İkincisi ise sıfırdan array oluşturma yöntemidir. Elimizde incelemek üzere bir verimiz olduğu zaman ihtiyacı en çok çözen yöntemdir Birkaç yöntemi birlikte inceleyelim.

* 0'lardan oluşan int tipinde 10 elemanlı tek boyutlu bir array oluşturalım:

In [9]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

* 3'e 5 ve 1'lerden oluşan bir matris yapısı tanımlayalım. '3'e 5' lafından da anlaşılacağı üzre iki boyutlu bir array oluşturacağız:

In [13]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

* İstediğimiz herhangi bir rakamda 3'e 5'lik bir matris olusturalım. Ben sadece 5'lerden oluşan bir matris yapmak istiyorum :

In [14]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

* 0'dan 30'e kadar 3'er 3'er artacak şekilde doğrusal bir dizi oluşturalım:

In [15]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

* İki değer belirleyelim ve bu iki değer aralığında istediğimiz kadar elemandan oluşan tek boyutlu bir array oluşturalım. Ben 0 ile 1 arasında tek boyutlu 10 tane değer olusturacağım. Dikkat etmemiz gereken nokta belirlediğimiz iki değer de bu arrayın elemanı olacaktır. Mesela benim örneğim için ilk değer 0,son değer ise 1 olacaktır.

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

* Ortalamasını ve standart sapmasını bildiğimiz bir array oluşturalım. Ben ortalaması 10 standart sapması 4 olan 3'e 4'lük iki boyutlu bir matris yapacağım.

In [17]:
np.random.normal(10,4,(3,4))

array([[10.04939045, 11.90520436, 12.87129109,  3.26253656],
       [ 4.84453322, 12.25406781,  8.98319334,  8.37841205],
       [ 7.95609427, 15.86771147,  7.48522295,  6.84047571]])

* Şimdi ise 3'e 3 iki boyutlu bir matris oluşturalım ve bu matrisimiz 0-10 arası integer değerlerden rastgele oluşsun :

In [18]:
np.random.randint(0,10,(3,3))

array([[4, 3, 3],
       [6, 3, 9],
       [2, 7, 3]])

### Not: Eğer oluşturduğumuz array'leri ileride kullanacaksak bu array'leri bir değişkene atamamız gerekir.

In [21]:
s=np.random.randint(10,size=10)
s  #s array'ini ekrana bastirmak istedigimizde Jupyter notebook'ta böyle yazmamız yeterli.

array([9, 3, 3, 8, 6, 2, 1, 1, 2, 0])

Oluşturduğumuz a array'i üzerinden işlemler yapalım.

* s array'inin boyutunu öğrenmek istersek :

In [22]:
s.ndim

1

* s array'inin boyut bilgisini öğrenmek istsersek :

In [23]:
s.shape

(10,)

* s array'inin eleman sayisini öğrenmek istersek :

In [24]:
s.size

10

* s array'inin veri tipini öğrenmek istersek :

In [25]:
s.dtype

dtype('int32')

### ndim shape size ve dtype için bir örnek daha yapalım. Bu seferki array'imiz ise iki boyutlu olsun.

In [27]:
m=np.random.randint(10,size=(4,2))
m

array([[7, 3],
       [9, 8],
       [7, 6],
       [2, 7]])

In [28]:
m.ndim

2

In [29]:
m.shape

(4, 2)

In [30]:
m.size

8

In [31]:
m.dtype

dtype('int32')

#### Array'lerde bilinmesi gereken bir diğer bilgi ise ;
#### * tek boyutlu array'in karşılığı vektör
#### * iki boyutlu veya daha fazla boyutlu array'lerin karşılığı ise matristir. Matrislerde parantez içinde ilk yazılan değer satırı ikinci yazılan değer ise sütunu temsil eder.

### [02. Reshaping \Yeniden Sekillendirme\ notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/02.%20Reshaping%20%5CYeniden%20Sekillendirme%5C)