<font color='green'>

# Yeniden Şekillendirme (Reshaping)

### Var olan bir array'in boyutlarını değiştirme işlemidir. Diğer bir adıyla _yapısal dönüşümdür_ de diyebiliriz.

In [1]:
import numpy as np

In [2]:
np.arange(1,10)  #1'den 10'a kadar sıralanan tek boyutlu array oluşturuldu.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10).reshape((3,3))  #1'den 10'a kadar sıralanan 3'e 3 matris oluşturalım.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Hatırlatma: .ndim fonksiyonu array'in fonksiyonunu verir.

In [6]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a.ndim

1

In [8]:
b=a.reshape((1,9))
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
b.ndim

2

### [03. Birleştirme 'Concatenation' notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/03.%20Birle%C5%9Ftirme%20'Concatenation'.ipynb)