<font color='green'>

# Birleştirme (Concatenation)

### Yapısı bilinen array'leri basitçe birleştirmek için kullanılır. Alt alta veya yan yana olacak şekilde birleştirme işlemi yapılır.

In [6]:
import numpy as np

### Tek boyutlu arraylerde (vektörlerde) birleştirme işlemi :

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b=np.array([4,5,6])
b

array([4, 5, 6])

#### Bu iki array'i birleştirelim :

In [10]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

#### Bir array daha oluşturalım ve bunu da birleştirelim :

In [9]:
c=np.array([7,8,9])
c

array([7, 8, 9])

In [13]:
np.concatenate([a,b,c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### İki boyutlu array'lerde (matrislerde) birleştirme işlemi :

In [15]:
x=np.array([[1,2,3],[4,5,6]])  #elle iki boyutlu bir array oluşturduk.
x

array([[1, 2, 3],
       [4, 5, 6]])

#### Satır bazında birleştirmek istersek :

In [18]:
np.concatenate([x,x])  #alt alta olacak şekilde birleştirelim.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

veya

In [21]:
np.concatenate([x,x],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

#### Sütun bazında birleştirmek istersek :

In [20]:
np.concatenate([x,x],axis=1)  #yan yana olacak şekilde birleştirdik.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### NOT: Anlaşılacağı üzere axis komutu eksen belirtmek için kullanılır. axis=0 olduğunda satır bazında (alt alta birleştirme), axis=1 olduğunda sütun bazında (yan yana birleştirme) yapılır. Eğer satır bazında birleştirme yapacaksak axis=0 yazmasak da olur çünkü axis'in default olarak ayarı zaten 0'dır.

#### Birbirinden farklı iki matrisi önce satır bazında sonrasında ise sütun bazında birleştirelim :

In [22]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [23]:
y=np.array([[5,6],[7,8]])
y

array([[5, 6],
       [7, 8]])

In [26]:
np.concatenate([x,y])  #satır bazında birleştirme

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
np.concatenate([x,y],axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### [04. Ayırma 'Splitting' notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/04.%20Ay%C4%B1rma%20'Splitting'.ipynb)