<font color='green'>

# 04. Ayırma (Splitting)

### Yapısı bilinen array'leri basitçe ayırmak için kullanacağımız yöntemlerdir.

In [1]:
import numpy as np

In [2]:
a=np.array([2,4,6,10,20,1,3,5])
a

array([ 2,  4,  6, 10, 20,  1,  3,  5])

### Bu array'i [2,4,6] , [10,20] ve [1,3,5] şeklinde 3'e ayırmak istersek :

In [3]:
np.split(a,[3,5])

[array([2, 4, 6]), array([10, 20]), array([1, 3, 5])]

### Peki oluşan bu 3 yeni array'i de tek seferde değişkenlere atamak istersek :

In [12]:
x,y,z=np.split(a,[3,5])

In [13]:
x

array([2, 4, 6])

In [14]:
y

array([10, 20])

In [15]:
z

array([1, 3, 5])

#### 3 yeni array elde etmiş olduk.

### İki boyutlu array'lerde (matrislerde) ayırma işlemi :

In [20]:
matris=np.arange(16).reshape(4,4)  #0'dan 16'ya sırayla değer alan 4'e 4 matris oluşturalım. 
matris

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### * İki boyutlu array'imizi 2.satırdan _öncesi ve sonrası_ şeklinde bölelim  :

In [21]:
np.vsplit(matris,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

#### Böldüğümüz iki parçayı da ileride kullanacağımızı varsayarak bir değişkene atamak istersek :

In [22]:
alt,üst=np.vsplit(matris,[2])

In [23]:
alt

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
üst

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### İki boyutlu array'imizi diklemesine ikiye bölmek istersek :

In [25]:
np.hsplit(matris,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

#### Böldüğümüz iki parçayı da ileride kullanacağımızı varsayarak bir değişkene atamak istersek :

In [26]:
sag,sol=np.hsplit(matris,[2])

In [27]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [28]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### [05. Sıralama 'Sorting' notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/05.%20S%C4%B1ralama%20'Sorting'.ipynb)