<font color='green'>
    
# Sıralama (Sorting)

## Array içerisindeki değerleri büyükten küçüğe sıralamak için kullanılan metottur.

In [1]:
import numpy as np

In [2]:
v=np.array([3,8,6,11,2,5])  #rastgele birkaç değer vererek bir array oluşturalım
v

array([ 3,  8,  6, 11,  2,  5])

####Küçükten büyüğe sıralayalım :

In [4]:
v.sort()
v

array([ 2,  3,  5,  6,  8, 11])

veya

In [5]:
np.sort(v)  #bu yöntem sayesinde ekstra olarak v'yi ekrana bastırmak istediğimi bildirmeme gerek kalmıyor.

array([ 2,  3,  5,  6,  8, 11])

### İki boyutlu array'lerde (matrislerde) sıralama işlemi :

In [7]:
matris=np.random.normal(20,5,(3,3))  #ortalaması 20 standart sapması 3 olan 3'e 3 matris oluşturalım
matris

array([[13.47196739, 16.39189996, 19.5659078 ],
       [21.29120268, 21.70406873, 20.0683672 ],
       [19.8815681 , 19.02982097, 16.14199203]])

#### Her bir satırı kendi içinde büyükten küçüğe sıralamak için :

In [9]:
matris.sort(axis=1)
matris

array([[13.47196739, 16.39189996, 19.5659078 ],
       [20.0683672 , 21.29120268, 21.70406873],
       [16.14199203, 19.02982097, 19.8815681 ]])

In [10]:
np.sort(matris,axis=1)

array([[13.47196739, 16.39189996, 19.5659078 ],
       [20.0683672 , 21.29120268, 21.70406873],
       [16.14199203, 19.02982097, 19.8815681 ]])

#### Her bir sütunu kendi içinde büyükten küçüğe sıralamak için :

Önce yeniden karışık bir matris hazırlayalım.

In [14]:
matris=np.random.normal(10,3,(4,4))  #ortalaması 10 standart sapması 3 olan 4'e 4 matris
matris

array([[ 7.01888109, 11.12980108,  3.09856182, 10.12296292],
       [10.61334027, 10.53074776, 12.66220352,  8.26253233],
       [ 8.48081747,  5.84297082,  8.10274906, 11.84693706],
       [14.37895617, 14.54409051, 11.79142913,  7.89933234]])

In [15]:
matris.sort(axis=0)
matris

array([[ 7.01888109,  5.84297082,  3.09856182,  7.89933234],
       [ 8.48081747, 10.53074776,  8.10274906,  8.26253233],
       [10.61334027, 11.12980108, 11.79142913, 10.12296292],
       [14.37895617, 14.54409051, 12.66220352, 11.84693706]])

veya

In [16]:
np.sort(matris,axis=0)

array([[ 7.01888109,  5.84297082,  3.09856182,  7.89933234],
       [ 8.48081747, 10.53074776,  8.10274906,  8.26253233],
       [10.61334027, 11.12980108, 11.79142913, 10.12296292],
       [14.37895617, 14.54409051, 12.66220352, 11.84693706]])

### [06. Index ile Elemanlara Erişme notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/06.%20Index%20ile%20Elemanlara%20Eri%C5%9Fme.ipynb)