<font color='green'>

# Index ile Elemanlara Erişme

**Bir elemanın listede kaçıncı sırada olduğu ve o elemanın index'i birbirinden farklı ancak ilişkili şeylerdir. İki terim arasındaki ilişkiyi açıklayalım:**

**Index her zaman gösterdiği elemanın sırasından '1' eksiktir.
Örneğin 0.index derken kastettiğimiz array'in 1.elemandır.
2.index demek 3.eleman demektir.**

**Basit gibi görünse de unutulmaması gereken önemli bir kuraldır. Bütün kodlama dillerinde geçerlidir.**

In [3]:
import numpy as np

In [7]:
x=np.random.randint(5,size=8) #0-5 arası int değer alabilen 8 elemanlı array oluşturalım.
x  

array([3, 2, 2, 3, 1, 4, 0, 1])

#### 0. index'teki elemanı görelim:

In [8]:
x[0]   

3

1. elemanı bize döndürdü.

#### 5. index'teki elemanı görelim:

In [9]:
x[5]

4

6. elemanı bize döndürdü.

#### Eğer array'in saymakla uğraşamayacağımız kadar çok elemanı varsa ve son elemanlardan birini istiyorsak bizi büyük bir çileden kurtararak tersten saymamızı sağlayan 'eksi index' in uygulamasını görelim :

In [11]:
x[-1]  #son elemanı görmek istiyorsak.

1

x[-1] = x[7]

In [12]:
x[-3]  #sondan 3.elemanı görmek istiyorsak.

4

x[-3]=x[5]

#### Eğer elemanda değişiklik yapmak istersek :

In [14]:
x[0]=58  #0. index'i yani 1. elemanı 58'e eşitledik.
x

array([58,  2,  2,  3,  1,  4,  0,  1])

### İki boyutlu array'lerde (matrislerde) index ile elemana erişme :

In [4]:
matris=np.random.randint(10,size=(3,5))
matris  #0-10 arası rastgele int deger alabilen 3'e 5 matris oluşturalım. 

array([[1, 9, 4, 3, 3],
       [2, 0, 7, 4, 2],
       [4, 0, 0, 7, 3]])

In [13]:
matris[0,0]  #endex'i 0 olan satırın ve endex'i 0 olan sütunun kesişimindeki eleman

1

In [14]:
matris[2,4]  #endex'i 2 olan satırın ve endex'i 4 olan sütunun kesişimindeki eleman

3

In [15]:
matris[1,3]=58  #endex'i 1 olan satırın ve endex'i 3 olan sütunun kesişimindeki elemanın değeri 58'e eşitlendi

In [16]:
matris

array([[ 1,  9,  4,  3,  3],
       [ 2,  0,  7, 58,  2],
       [ 4,  0,  0,  7,  3]])

### Görüldüğü üzere 4 olan değerimiz 58 oldu.

Hatırlayacağımız üzere array'lerimiz tek tip olmak zorunda idi. Örneğin array'imizin tipi integer değer ise sonradan array'in bir elemanına dışarıdan bir float değer atasak dahi ondalık değerleri siler,yok olarak görür ve int tip olarak array'e ekler. Örnek vermek gerekirse 'matris' array'i int tipindedir. Bir elemanına float değer ataması yapmayı deneyelim : 

In [17]:
matris[1,1]=42.35
matris

array([[ 1,  9,  4,  3,  3],
       [ 2, 42,  7, 58,  2],
       [ 4,  0,  0,  7,  3]])

42.35 in ondalık kısmını attı ve sadece 42 kısmını array'e ekledi.

### [07. Array'in Altkümelerine Erişme 'Slicing' notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/07.%20Array'in%20Altk%C3%BCmelerine%20Eri%C5%9Fme%20'Slicing'.ipynb)