<font color='green'>

# Array'lerin Altkümelerine Erişme (Slicing)

### Matematikten bildiğimiz altküme işlemini Numpy kütüphanesi ile python üzerinden gerçekleyeceğiz. Öncelikle *altküme* kavramını açıklayalım.

#### Altküme : Bir A kümesinin bütün elemanları B kümesinin de elemanları ise "A kümesi B kümesinin alt kümesidir" denir. Şimdi hatırlatmak için basit bir örnek verdikten sonra işin bizi ilgilendiren kod kısımlarına geçelim

![](https://i.imgur.com/nNq7C46.jpg)

In [1]:
import numpy as np

In [13]:
x=np.arange(10,20,1)  #10'dan 20'ye kadar olan sayılarla bir array oluşturalım.
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### * x array'inde 0. index'ten 4. indix'e kadar git diyelim :

In [14]:
x[0:4]

array([10, 11, 12, 13])

veya başka bir gösterim ile

In [15]:
x[:4]

array([10, 11, 12, 13])

#### * x array'inde 0. index'ten başla ve  dizinin sonuna kadar 2'şer atlayarak git diyelim :

In [16]:
x[0::2]

array([10, 12, 14, 16, 18])

### İki boyutlu array'lerde slicing işlemi :

In [20]:
matris = np.random.randint(5,size=(4,4)) #0 ile 5 arası değer alabilen 4'e 4 bir matris tanımlayalım.
matris

array([[2, 0, 1, 0],
       [3, 1, 4, 1],
       [0, 2, 4, 0],
       [0, 3, 2, 4]])

## Önemli Not : matris arrayler'inde ister array oluştururken ister array'lere erişirken olsun her zaman önce yazılan değerler satırı ikinci olarak yazılan değerler sütunları temsil eder.

#### matris array'inin tüm satırlarının ve sadece 0. index'e denk gelen sütununun kesişimlerini göstermesini isteyelim :

In [22]:
matris[:,0]

array([2, 3, 0, 0])

Her satırın 0. index'e sahip olan elemanınlarını gösterdi.

### NOT: 
* [:] şeklinde başına ve sonuna değer almıyorsa baştan sona kadar git demektir. 
* [2:] şeklinde sadece başında değer varsa 2. index'ten başlayarak sona kadar git demektir.
* [:3] şeklinde sadece sonunda değer varsa baştan 3. index'e kadar git demektir.

#### matris array'inin tüm satırlarının ve sadece 1. index'e denk gelen sütununun kesişimlerini göstermesini isteyelim :

In [26]:
matris[:,1]

array([0, 1, 2, 3])

Her satırın 1.index'e sahip elemanını gösterdi.

### Sadece satır veya sütun yerine ikisine de erişerek işlem yapalım :

In [28]:
matris #matris array'ini hatırlayalım.

array([[2, 0, 1, 0],
       [3, 1, 4, 1],
       [0, 2, 4, 0],
       [0, 3, 2, 4]])

#### satırları 0 ve 2. index arası sütunları ise 2'den son elemana kadar alalım :

In [27]:
matris[:2,2:]

array([[1, 0],
       [4, 1]])

#### Tüm satırları alalım ve sütun olarak da 0 ve 23. index arasını alalım :

In [30]:
matris[::,:3]

array([[2, 0, 1],
       [3, 1, 4],
       [0, 2, 4],
       [0, 3, 2]])

Burada farklı bir syntax yapısı daha görüyoruz ancak değişen hiçbir şey yok.

* **matris[::,:3]**
* **matris[:,:3]**
* **matris[:,0:3]**
* **matris[0:,:3]**
* **matris[0:,0:3]**

Hepsi aynı şeyi ifade etmektedir.

#### Bu sefer örnek olarak satırları 1 ve 3. index'e göre, sütunları ise 0 ve 2. index'e göre alalım :

In [31]:
matris[1:3,0:2]

array([[3, 1],
       [0, 2]])

#### matris array'inin tüm satırlarının ve sadece 0. index ile 3. index arasına denk gelen sütunların kesişimlerini göstermesini isteyelim :

In [24]:
matris[:,0:3]

array([[2, 0, 1],
       [3, 1, 4],
       [0, 2, 4],
       [0, 3, 2]])

her satırın 0,1 ve 2. index'ine denk gelen elemanları gösterdi.

[08. Altküme Üzerinde İşlem Yapma notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/08.%20Altk%C3%BCme%20%C3%9Czerinde%20%C4%B0%C5%9Flem%20Yapma.ipynb)