<font color='green'>

# Altküme Üzerinde İşlem Yapma

### Matematikten bildiğimiz altküme işlemini Numpy kütüphanesi ile python üzerinden gerçekleyeceğiz. Öncelikle *altküme* kavramını açıklayalım.

#### Altküme : Bir A kümesinin bütün elemanları B kümesinin de elemanları ise "A kümesi B kümesinin alt kümesidir" denir. Şimdi hatırlatmak için basit bir örnek verdikten sonra işin bizi ilgilendiren kod kısımlarına geçelim

![](https://img.eba.gov.tr/108/372/5c4/0c7/476/684/c1f/834/7e0/ea5/fdd/0e7/d81/ed6/003/1083725c40c7476684c1f8347e0ea5fdd0e7d81ed6003_200_200.png/800/800)

In [1]:
import numpy as np

### 10'a kadar int deger alabilen 4'e 4 bir matris oluşturalım.

In [3]:
matris=np.random.randint(10,size=(4,4))
matris

array([[0, 1, 8, 6],
       [8, 7, 5, 9],
       [8, 9, 7, 1],
       [9, 6, 5, 5]])

In [6]:
altküme=matris[0:3,0:4]  #0'dan 2'ye kadar olan satırları ve 0'dan 4'e kadar olan sütunları değişkene ata.
altküme 

array([[0, 1, 8, 6],
       [8, 7, 5, 9],
       [8, 9, 7, 1]])

In [9]:
altküme=matris[0:2,0:2]  #0'dan 2. index'e kadar olan satırları ve 0'dan 2.index'e kadar olan sütunları değişkene ata.
altküme

array([[0, 1],
       [8, 7]])

#### 'matris' array'inden istediğimiz elemanları 'altküme' adını verdiğimiz başka bir değişkene atadık. Peki matrisimizde o elemanlar hala bulunuyor mu? Bakalım :

In [7]:
matris

array([[0, 1, 8, 6],
       [8, 7, 5, 9],
       [8, 9, 7, 1],
       [9, 6, 5, 5]])

#### Görüldüğü üzere 'matris' array'inde herhangi bir degişiklik olmamıştır.

### Altkümede elemanın değerini değiştirmek istersek : 

In [11]:
altküme[0,0]=58
altküme[1,1]=58
altküme

array([[58,  1],
       [ 8, 58]])

Endex'i "0.satır 0.sütun" ve "1.satır 1.sütun" olan iki elemanın değerini 58'e eşitledik.

In [12]:
altküme[0,1]=59
altküme

array([[58, 59],
       [ 8, 58]])

Endex'i 0.satır ve 1.sütun olan elemanın değerini 59 yaptık.

### Peki altkümede yaptığımız değişiklikler asıl kümemizi etkiler mi? Görelim :

In [14]:
matris

array([[58, 59,  8,  6],
       [ 8, 58,  5,  9],
       [ 8,  9,  7,  1],
       [ 9,  6,  5,  5]])

#### Buradan da anlaşılacağı gibi alt kümede yaptığımız değişiklikler ana kümemizi doğrudan etkiler. Yaptığımız her değişiklik ana kümede de kendini gösterdi.

### Eğer altkümede yaptığımız değişikliklerin ana kümeyi etkilemesini (bozmasını) istemiyorsak :

In [15]:
matris=np.random.randint(10,size=(4,4))  #önce matrisimizi yeniden oluşturalım.
matris

array([[5, 8, 4, 5],
       [3, 2, 7, 1],
       [0, 9, 8, 5],
       [2, 9, 6, 0]])

In [18]:
altküme=matris[0:2,0:2].copy()  #istenilen aralıktaki değerleri kopyala ve değişkene ata.
altküme

array([[5, 8],
       [3, 2]])

In [19]:
altküme[0,0]=58
altküme[1,0]=58
altküme

array([[58,  8],
       [58,  2]])

#### Şimdi yeniden ana kümemiz olan 'matris' array'imizi görelim. Değişiklik olup olmadığını kontrol edelim :

In [20]:
matris

array([[5, 8, 4, 5],
       [3, 2, 7, 1],
       [0, 9, 8, 5],
       [2, 9, 6, 0]])

#### Beklenildiği üzere kümemiz bozulmadan kendini korudu. Bunun nedeni ise altküme işlemi yapar gibi eleman seçmemiz ancak elemanları almak yerine kopyalayıp başka bir değişkene bu değerleri atamış olmamızdır. Tüm değişiklikler artık sadece bu değişken üzerinde yapılır.

### [09. Fancy Index ile Elemanlara Erişim notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/09.Fancy%20Index%20ile%20Elemanlara%20Eri%C5%9Fim.ipynb)