<font color='green'>

# Fancy Index ile Elemanlara Erişim

### Array'lerde daha ileri düzey eleman seçme imkanları verir.

### * Öncelikle tek boyutlu array'lerde (vektörlerde) fancy index'i görelim :

In [1]:
import numpy as np

In [6]:
v=np.arange(0,30,3)  #.arrange fonksiyonu sayesinde 0'dan 30'a kadar 3'er 3'er saydığımız elemanları almış olduk.
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
v[0]  #0.index'teki elemanı göstermesini istiyoruz.

0

In [9]:
v[3]  #3.index'teki elemanı göstermesini istiyoruz.

9

#### Eğer teker teker görmek yerine birden çok index'i bir arada görmek istersek :

In [10]:
[v[2],v[4],v[6]]  #2 4 ve 6.index'teki elemanları göster.

[6, 12, 18]

#### Bir array yardımıyla başka bir array'in elemanlarına erişmek istersek :

In [11]:
a=[1,2,3]
a

[1, 2, 3]

In [12]:
v[a]  #1,2 ve3.index'teki elemanları göster.

array([3, 6, 9])

#### NOT: Yapılan bu işleme _Fancy Index_ denir. Dikkat edeceğinizi üzere fancy adında özel bir fonksiyon çağırmadık.

### * İki Boyutlu array'lerde (matrislerde) Fancy Index

In [14]:
matris=np.arange(9).reshape((3,3))  #0'dan 9'a kadar değer alabilen 3'e 3 matris oluşturulsun.
matris

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
satir=np.array([0,1]) 
sutun=np.array([1,2])

Bir matrisin içine ilk yazılan değer satırı ikinci yazılan değer ise sütun bilgisini bize verir.

* satir matrisini ele almak gerekirse içine aldığı değerleri : ([0,1])
    * 0.index'e denk gelen satirin 1.index'e denk gelen sütununun bulunduğu yeri işaret ediyor. Bu da 1.satırın 2.sütunundaki elemanı demektir. : 1

* sutun matrisini ele almak gerekirse içine aldığı değerler : ([1,2])
    * 1.index'e denk gelen satirin 2.index'e denk gelen sütununun kesiştiği yeri işaret ediyor. Bu da 2.satırın 3.sütunundaki elemanı demektir. : 5


In [19]:
matris[satir,sutun]

array([1, 5])

### Şimdi ise _basit index_ ile _fancy index'i_ bir arada kullanalım.

In [18]:
matris[0,[1,2]]  #sol taraftaki basit index sağ taraftaki ise fancy index'tir.

array([1, 2])

Bu örnekte 'basit index ile array'in 0.index'inde bulunan elemanı ve fancy index ile 1.index'e denk gelen satirin, 2.index'e denk gelen sütununda bulunan elemanı ekrana yazdır' dedik.

### Bu sefer de slice ile fancy index'i bir arada kullanalım.

In [21]:
matris  #Önce matrisimizi hatırlayalım.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
matris[0:,[1,2]]  #sol taraf slice sağ taraf ise fancy index

array([[1, 2],
       [4, 5],
       [7, 8]])

* Slice ile 1.satıra erişmek için 0.index ve tüm sutunlar demiş olduk.
* Fancy index ile 1 ve 2. index'lere denk gelen sütunları seçmiş olduk.

Sonuç olarak bu iki şartın kesişimindeki elemanları ekrana bastırdık.

### [10. Karşılaştırma Operatörü notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/10.%20Kar%C5%9F%C4%B1la%C5%9Ft%C4%B1rma%20Operat%C3%B6rleri.ipynb)