<font color='green'>

# Koşullu Eleman İşlemleri

### Matematikteki anlamıyla bire bir aynıdır. Herhangi bir kodlama dilini bilen arkadaşların bu konuyu çok rahat kavrayacağından eminim. Her kodlama dilinde olan mantık burada de geçerli.  Ancak bu konu özelinde konu anlatımı yapmak yerine örneklerin daha açıklayıcı olacağını düşünüyorum. O yüzden _karşılaştırma operatörleri tablomuzu_ inceleyelim ve örneklere geçelim :

![](https://lh3.googleusercontent.com/proxy/_qIqQN-Rj3ZmOcBuRNZvVvyJMgkF8aferro26Rmz83zkz_tBN4Dt4SVdbvWNukZSRkikFjt-cRw695IakOnvl01L1nTuGbgmxZ19gqdMKiBZ3PkI29PAdRuNlRL6Aex828OsZss5Qwk)

> Tabloyu hazır aldım. Kaynağı : http://tayfunkadir.com/Makaleler/C-Operatorler-Mantiksal-Operatorler-ve-Karsilastirma-Operatorleri/75

In [1]:
import numpy as np

In [9]:
a=np.array([5,7,10,16,3])
a

array([ 5,  7, 10, 16,  3])

In [10]:
a<3

array([False, False, False, False, False])

Bu yazılış şekli ile bize True,False şeklinde bir çıktı veriyor.

In [11]:
a<=10

array([ True,  True,  True, False,  True])

Görüldüğü üzere 10'dan küçük veya 10'a eşit olan değerler 'True', diğer değerler 'False' şeklinde döndü.

#### Ancak biz True ya da False bilgisi yerine array'imizde koşulu sağlayan değerlerin döndürülmesini istersek :

In [12]:
a[a>7]

array([10, 16])

array'deki elemanlardan 7'den büyüklerini almış olduk.

In [14]:
a[a!=10]

array([ 5,  7, 16,  3])

array'deki elemanlardan 10'a eşit olmayanları döndürmesini sağlar.

#### Tabloda verilen her _karşılaştırma operatörü_ için işlemler bu şekilde kullanılabilir.

[11.Numpy'da Matematiksel İşlemler notlarına geçmek için tıklayınız](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/11.%20Numpy'da%20Matematiksel%20%C4%B0%C5%9Flemler.ipynb)