<font color='green'>

# Numpy'da Matematiksel İşlemler

### Bu notta 4 işlem ( toplama,çıkarma,çarpma ve bölme) ile birlikte üs alma, mod alma, logaritmik işlemler ve mutlak değer alma gibi matematik işlemlerinin bir çoğunu inceleyeceğiz. 

### Bu işlemler için Numpy kütüphanesinin altındaki fonksiyonları kullanacağız. Bu fonksiyonlar _kısaltmasız olarak_ ingilizceden alınma kelimelerden oluşur. Fonksiyonları çağırırken bu kelimeleri kullanacağımız için ve ezber yapmamak adına aşağıdaki tabloda kelimeler ve anlamları bulunmaktadır :

![](https://imgur.com/YeySwLf.png)

#### Şimdi bir array oluşturalım ve yukarıda bahsettiğimiz fonksiyonları sırasıyla uygulamaya koyalım.

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
np.subtract(a,1)  #'a array'inin elemanlarından 1 çıkar' diyoruz.

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
np.add(a,1)  #'a array'inin elemanlarına 1 ekle' diyoruz.

array([2, 3, 4, 5, 6, 7, 8])

In [13]:
np.multiply(a,5)  #'a array'inin elemanlarını 5 ile çarp' diyoruz.

array([ 5, 10, 15, 20, 25, 30, 35])

In [14]:
np.divide(a,5)  #'a array'inin elemanlarını 5 ile böl' diyoruz.

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4])

In [15]:
np.power(a,2)  #'a array'inin elemanlarının 2. kuvvetlerini al' diyoruz.

array([ 1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [16]:
np.mod(a,3)  #'a array'inin elemanlarının 3'e göre modunu al' diyoruz.

array([1, 2, 0, 1, 2, 0, 1], dtype=int32)

In [19]:
eksi=np.array([-1,-2,-3,-4])  #mutlak değer işlemi için eksilerden oluşan bir array daha oluşturalım.
eksi

array([-1, -2, -3, -4])

In [20]:
np.absolute(eksi)

array([1, 2, 3, 4])

### Trigonometrik işlemler yapmak istersek :

In [21]:
np.sin(90)  

0.8939966636005579

In [22]:
np.cos(90)

-0.4480736161291701

### Logaritmik işlemler yapmak istersek :

In [24]:
a  #a array'imizi hatırlayalım.

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

In [41]:
np.log10(a)  #'a array'inin elemanlarının 10'a göre logaritmasını göre al' dedik.

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804])

### Ortalama bulmak istersek :

In [32]:
a  #a array'imizi hatırlayalım.

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
np.mean(a)

4.0

### Sadece veri içindeki elemanları birbiriyle işlem yaptırmak istersek :

In [34]:
a.sum()  #'a array'i içerisindeki elemanları topla' dedik.

28

In [36]:
a.min()  #'a array'i içerisindeki elemanların en küçüğünü bul' dedik.

1

In [37]:
a.max()  #'a array'i içerisindeki elemanların en büyüğünü bul' dedik.

7

[12.Numpy'da İki Bilinmeyenli Denklem Çözümü notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/12.%20Numpy'da%20iki%20bilinmeyenli%20denklem%20%C3%A7%C3%B6z%C3%BCm%C3%BC.ipynb)