<font color='green'>

## Numpy'da iki bilinmeyenli denklem çözümü

#### Çok bilinmeyenli denklemi çözebilmemiz için elimizde ' _en az_ '  bilinmeyen sayısı kadar denklem sayısı bulunmalıdır.

![](https://lh3.googleusercontent.com/proxy/sLaQbm1MgS3hsxcsjJiMt84l5S19qIgcM7Hk0gxfpEBwCtUwr5y-3P6NjaMJ5DnGJkIk-bXpt2J4wcr1f25-W29v9noCnOo8pE4xLOIZyABAfEHSHNxDlEtaPXTWSV3XfeMkKLfTLt1aB1jHvj5CJJonHpP38C1_zmobLA)
>  m>=n kuralı sağlanmadıkça denklemdeki bilinmeyenler çözülemez.
>>  Ben alışkanlıklarımdan dolayı sabitler matrisine çözüm,sonuç matris ifadelerini kullanacağım. İkisi de aynı ifadedir.

#### Örneğin elimizde 

####  5*x0 + x1 =12
#### x0 + 3* x1 = 10

#### şeklinde iki bilinmeyenli iki tane denklemimiz olsun.

##### Bizim için denklemde önemli olan iki kısım vardır: 
* 1. Bunlardan ilki bilinmeyenlerin katsayılarıdır. Bizim için x0 ve x1'in katsayıları
*  2. İkincisi ise sonuçlar matrisi adını verdiğimiz denklemin sağında kalanlar. Bizim için sonuçlar matrisi 12 ve 10'u içerir.

### Şimdi anlattıklarımızı pratiğe dökelim :

In [2]:
import numpy as np

Önce katsayılar matrisini oluşturacağız. [5,1] dediğimiz kısımda birinci denklemin katsayılarından, [1,3] dediğimizde de ikinci denklemin katsayılarından geldiğini bilmeliyiz.

In [7]:
a=np.array([[5,1],[1,3]])
a  #katsayılar matrisi

array([[5, 1],
       [1, 3]])

In [5]:
b=np.array([12,10])
b  #sonuçlar matrisi

array([12, 10])

Sıra x0 ve x1 değişkenklerimizi bulmaya geldi. Bu işlemi yaparken elde edeceğim iki sonucu ileride kullanacağımı varsayarak bir değişkene atıyorum.

In [8]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

İlk sonuç x0'in ikinci sonuç ise x1'in değeridir.

### [13. Matrislerde Çarpma İşlemi notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Numpy%20K%C3%BCt%C3%BCphanesi/13.%20Matrislerde%20%C3%87arpma%20%C4%B0%C5%9Flemi.ipynb)