<font color='green'>

# Matrislerde Çarpma İşlemleri

###   Bu notta numpy kütüphanesi ile _skaler ve vektörel_ çarpım gibi matematiksel işlemlerin üzerinde duracağız. Matris dediğimiz için sadece iki veya daha fazla boyuttaki array'lerle ilgileneceğiz. Ya da bir diğer deyişle tek boyutlu array'ler bu konu başlığı altında bulunmayacaktır.

In [31]:
import numpy as np

In [4]:
a= np.array([[(1,2),(3,4)]])
b= np.array([[(5,6),(7,8)]])

Önce bu iki boyutlu 'a' ve 'b' array'lerimizi görelim:

In [5]:
a

array([[[1, 2],
        [3, 4]]])

In [6]:
b

array([[[5, 6],
        [7, 8]]])

#### *  İki vektörün çarpımı :

bu iki vektörün çarpımını c'ye eşitleyelim ve c array'ini ekranda bastıralım.

In [8]:
c=np.dot(a,b)
c

array([[[[19, 22]],

        [[43, 50]]]])

aynı işlemi farklı bir syntax yapısı ile yapalım:

In [9]:
c=(a.dot(b))
c

array([[[[19, 22]],

        [[43, 50]]]])

**HATIRLATMA:** Lineer cebir dersinde gördüğümüz iki matrisin çarpım kuralı :

![](matas.png)

Bizim tanımladığımız 'a' ve 'b' array'lerine göre işlemleri düzenlersek:

![](cozum.jpeg)

> Yazının kötülüğünden dolayı özür dilerim :D

Görüldüğü üzere sonuçlar aynı çıktı.

#### * Tek boyutlu bir array'in (vektörlerün) skaler çarpımı :

In [19]:
vektör=np.array([1,2,3,4,5]) 
vektör

array([1, 2, 3, 4, 5])

In [20]:
vektör+2

array([3, 4, 5, 6, 7])

In [24]:
vektör-1

array([0, 1, 2, 3, 4])

In [21]:
vektör*2

array([ 2,  4,  6,  8, 10])

In [22]:
vektör/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [23]:
vektör*3/6

array([0.5, 1. , 1.5, 2. , 2.5])

In [27]:
vektör**3  #küp alma işlemi --> ** üslü işlemidir. **2 deseydik kare aldırırdık.

array([  1,   8,  27,  64, 125], dtype=int32)

In [29]:
vektör%2  #vektör array'inin içindeki elemanların 2'ye göre modunu aldık.

array([1, 0, 1, 0, 1], dtype=int32)

#### * İki boyutlu bir array'in (matrisin) skaler çarpımı:

In [33]:
matris=np.array([[(1,2),(3,4)]])
matris

array([[[1, 2],
        [3, 4]]])

In [34]:
np.multiply(matris,2)  #v*2 ile aynı işi görür.Syntax'ı farklı olduğu için buna da gözümüzün alışması adına son örneklerde bu şekilde kullanacağım.

array([[[2, 4],
        [6, 8]]])

In [35]:
np.add(matris,2)

array([[[3, 4],
        [5, 6]]])

In [36]:
np.divide(matris,10)

array([[[0.1, 0.2],
        [0.3, 0.4]]])

Örnekler sayısını siz de arttırabilirsiniz. Ben elimden geldiğince hepsinden birer tane örnek olacak şekilde yapmaya çalıştım.

## Numpy kütüphanesi hakkında topladığım notların sonuna geldim. Umarım faydalı olmuştur. Yeni bilgiler edindikçe ve fırsat buldukça güncellemeler yapmaya çalışacağım. Eşlik eden herkese teşekkürler :)