<font color='green'>

## 05. Pandas DataFrame Eleman İşlemleri

In [10]:
import numpy as np
import pandas as pd

In [4]:
s1=np.random.randint(10,size=5)
s1

array([0, 2, 0, 3, 4])

In [5]:
s2=np.random.randint(10,size=5)
s2

array([0, 6, 1, 3, 3])

In [8]:
s3=np.random.randint(10,size=5)
s3

array([7, 1, 5, 6, 2])

### Şimdi bir sözlük yapısı tanımlayalım ve bu sözlük yapısını bir pandas dataframe'inin içine koyalım.

In [20]:
sozluk={"var1" : s1, "var2" : s2, "var3" : s3}
sozluk

{'var1': array([0, 2, 0, 3, 4]),
 'var2': array([0, 6, 1, 3, 3]),
 'var3': array([7, 1, 5, 6, 2])}

In [21]:
dataf=pd.DataFrame(sozluk)
dataf

var1  var2  var3
0     0     0     7
1     2     6     1
2     0     1     5
3     3     3     6
4     4     3     2

### Dataframe'i oluşturduğumuza göre eleman işlemlerine geçelim :

### 0'dan 1. sütuna kadar olan değerleri bastıralım.

In [12]:
dataf[0:1]

var1  var2  var3
0     0     0     1

### Index'lere değer atayalım.

In [22]:
dataf.index=["a","b","c","d","e"]

### c indexinden a indexine kadar git diyelim.

In [14]:
dataf["c":"e"]

var1  var2  var3
c     0     1     8
d     3     3     0
e     4     3     5

### DataFrame'den eleman silme :

In [15]:
dataf.drop("a",axis=0)

var1  var2  var3
b     2     6     1
c     0     1     8
d     3     3     0
e     4     3     5

> **axis=0 sayesinde a'nın bulunduğu satırı silmek istediğimizi belirttik.**

### Şimdi dataf veri setini tekrardan ekrana yazdıralım.

In [16]:
dataf

var1  var2  var3
a     0     0     1
b     2     6     1
c     0     1     8
d     3     3     0
e     4     3     5

### Görüldüğü üzere .drop() yaptığımızda asıl veri setimizde kalıcı bir değişiklik olmaz.

### Eğer sildiğimiz zaman ana dataframe'den de silinsin istersek :

In [23]:
dataf.drop("a",axis=0, inplace=True)
dataf

var1  var2  var3
b     2     6     1
c     0     1     5
d     3     3     6
e     4     3     2

### 'inplace' argümanının görevi dataframe üzerinde yapılan değişikliğin kalıcı olmasını sağlamaktır.

### Görüldüğü üzere a satırını sildik ve bu kalıcı bir değişiklik oldu.

### Tek seferde birden fazla satır silmek istersek (fancy metodu kullanılır.) :

In [24]:
l={"c","e"}

In [25]:
dataf.drop(l, axis=0)

var1  var2  var3
b     2     6     1
d     3     3     6

> **Kalıcı olarak silmedik.**

> **Fancy metodu neden önemlidir ?
	dataf[0:2]["var1","var2"] şeklinde elemanlara erişemeyiz.Erişmek için fancy'ye almamız gerekir.
		dataf[0:2][["var1","var2"]]**

### Degiskenler için :

#### Hatırlatma :

In [26]:
"var1" in dataf

True

In [29]:
liste=["var1","var2","var4"]
for i in liste :
	print(i in dataf)

True
True
False


> **Bu blok yapısının türkçesi :                       
    'in' değişkeni liste içinde gezsin ve gezerken dataf içinde
    olup olmadıklarını sorgulasın sonrasında ekrana bassın.**

### var1 ve var2 şeklinde değişkenlerimiz olduğu için True bilgisi döndü ancak veri setimizde var4 değişkeni olmadığı için onun çıktısını False olarak görüyoruz.

### Yeni bir değişken tanımlayalım ama bu değişkeni dataframe'de yer alan değişkenler üzerinde yapalım. Mesela 'var4' değişkeni oluşturalım ve bu değişkeni 'var1' ve 'var2' nin çarpımından elde ederek yapalım. Ama öncesinde elimizdeki veri setini hatırlayalım :

In [30]:
dataf

var1  var2  var3
b     2     6     1
c     0     1     5
d     3     3     6
e     4     3     2

In [31]:
dataf["var2"]

b    6
c    1
d    3
e    3
Name: var2, dtype: int32

In [34]:
dataf["var4"]= dataf["var1"] * dataf["var2"]  
dataf

var1  var2  var3  var4
b     2     6     1    12
c     0     1     5     0
d     3     3     6     9
e     4     3     2    12

> **Bir elemana erişmek istediğimizi köşeli parantez ile belirttik. Ancak 'var4' şeklinde bir elemanımız olmadığı için bunu yeni bir değişken oluşturma olarak kabul ediyor.**

### Değişken oluşturmayı gördük. Şimdi ise değişken silmeye bakalım :

In [35]:
dataf.drop("var4",axis=1)

var1  var2  var3
b     2     6     1
c     0     1     5
d     3     3     6
e     4     3     2

### 'var4' değişkenini (sütununu) silmek için axis=1 dedik. Ancak inplace kullanmadığımız için geçici bir silme elde edeceğiz. Görelim :

In [37]:
dataf

var1  var2  var3  var4
b     2     6     1    12
c     0     1     5     0
d     3     3     6     9
e     4     3     2    12

### Tek seferde birden fazla satırı geçici olarak silelim :

In [38]:
liste=["var2","var3"]
dataf.drop(liste,axis=1)

var1  var4
b     2    12
c     0     0
d     3     9
e     4    12

### var2 ve var3 değişkenleri silindi.

### [06. Gözlem ve Değişken Seçimi 'loc ve iloc' notlarına geçmek için tıklayınız.](https://github.com/semihstp/Veri-Bilimi-Not-Defterim/blob/master/Pandas%20K%C3%BCt%C3%BCphanesi/06.%20G%C3%B6zlem%20ve%20De%C4%9Fi%C5%9Fken%20Se%C3%A7imi%20'loc%20ve%20iloc'.ipynb)